### ISSUE TITLE
Inspect immutability of type parameters of Immutable Container Types?

### ISSUE THREAD

**Issue by omsmith** [Brightspace/D2L.CodeStyle#425]
I'm sure y'all know this already, but I realized when I was refactoring some code that I could use `ImmutableDictionary<T, U>` where `T` and `U` are NOT `[Immutable]`, but I couldn't make an equivalent custom class, needing `MyImmutableDictionary<[Immutable] T, [Immutable] U>`.

So, current immutable container type inspection doesn't check the type parameters. I'm sure that was a conscious choice when introducing generic inspection, but not something I paid any mind to.

**Comment by omsmith** [comment]
I mean, it looks like it should be doing it already, but.... *shrug*
https://github.com/Brightspace/D2L.CodeStyle/blob/df45a9a589c11bf5bceed8df9ba690401717e494/src/D2L.CodeStyle.Analyzers/Immutability/ImmutableGenericDeclarationAnalyzer.cs#L76-L90

**Comment by j3parker** [comment]
Sorry for not looking at this when you opened it. We talked a bit in person recently.

It's true that currently it's impossible to write a class like `ImmutableArray<T>` or `ImmutableDictionary<K, V>`. Those are handled specially as "container types". Owen was also missing that `ImmutableArray<MutableThing>` is intentionally allowed by the analyzer. It just isn't regarded as `[Immutable]`.

## What I'd like to do

What I've been planning to do is change how our analysis works so that:

```cs
[Immutable]
public struct MyImmutableArray<[Immutable]T> {
```

is how you'd create your own "container" type. The way this should read is that `MyImmutableArray<T>` is `[Immutable]` iff `T` is as well. If there is no `[Immutable]` attribute on a generic parameter like this:

```cs
[Immutable]
public class WrapperOfThings<T> : IFactory<T> where T : IThing {
```

what we're saying is that `WrapperOfThings<T>` is immutable independent of `T`. The last case is `[Immutable]` on generic parameters of a non-`[Immutable]` thing:

```cs
public class Foo<[Immutable]T> {
```

I can't think of a good meaning to this compatible with adding `[Immutable]` to `Foo`. So I plan to make this an error (and likewise for generic method type parameters.)

## What does this buy us?

The behaviour for `ImmutableArray<T>` has proven to be very effective and we could make that less special and give ourselves that power (@omsmith had a case of wanting to use it.) It would require significantly less code to support this and would be in fact backwards compatible with our current behaviour.

## What do we lose?

The ability to make a generic class that can only be used to construct `[Immutable]` things. I don't actually think this is valuable. It's not necessary for our current analysis (proven by the new semantics being backwards compatible.)

## Conclusion

There is a weaker semantics for `[Immutable]` type parameters that is strong enough for everything we are currently doing. It will make it easier to write good `[Immutable]` generic classes. Unifying the behaviour of container types and generic immutable stuff will simplify the analyzer.

**Comment by j3parker** [comment]
Codified this in #583
